console.log(2 + 2 === 4)
console.log(2 + 2 === '4')
console.log(2 + 2 == '4')
console.log(Number('4'))
console.log(Number('0'))
console.log(NaN)
console.log(NaN != NaN)
console.log(Infinity == Infinity)
console.log(1/0 == 2/0)
console.log(2 * null)
console.log(2 + null)
console.log(7)
console.log(null || 7)
console.log('4')
console.log('')